export const menuItemMock = [
  {
    id: 1,
    name: "Pizza Margarita",
    description: "Pizza clásica con salsa de tomate y mozzarella",
    price: 8500,
    available: true,
    category: "Pizza",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 3,
    name: "Espaguetis a la Boloñesa",
    description: "Pasta con salsa de carne tradicional",
    price: 9500,
    available: true,
    category: "Pasta",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 5,
    name: "Coca-Cola",
    description: "Refresco clásico",
    price: 5500,
    available: true,
    category: "Bebidas",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 6,
    name: "Agua Mineral",
    description: "Agua natural sin gas",
    price: 5500,
    available: true,
    category: "Bebidas",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 7,
    name: "Café Espresso",
    description: "Café negro fuerte",
    price: 6000,
    available: true,
    category: "Bebidas",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 2000,
    name: "Té Verde",
    description: "Infusión de hojas de té verde",
    price: 1800,
    available: true,
    category: "Bebidas",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
];
